// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

Palette disclaimer_pal[] = {
    /* PALETTE 00 */ {
        /* 00 */ TO_RGB555(0xffffff),
        /* 01 */ TO_RGB555(0x081842),
        /* 02 */ TO_RGB555(0x000000),
        /* 03 */ TO_RGB555(0xef5a18),
        /* 04 */ TO_RGB555(0x31216b),
        /* 05 */ TO_RGB555(0x294263),
        /* 06 */ TO_RGB555(0x293942),
        /* 07 */ TO_RGB555(0xadadbd),
        /* 08 */ TO_RGB555(0x7b8494),
        /* 09 */ TO_RGB555(0x213142),
        /* 10 */ TO_RGB555(0x00ffff),
        /* 11 */ TO_RGB555(0xefa510),
        /* 12 */ TO_RGB555(0xefefef),
        /* 13 */ TO_RGB555(0x183152),
        /* 14 */ TO_RGB555(0x1842de),
        /* 15 */ TO_RGB555(0x8c4a10)
    }
};
