// Generated by N2T

#include "global.h"
#include "graphics.h"
#include "glee_prologue_anim_cells.inc.c"

struct Animation anim_glee_prologue_title[] = {
	/* 000 */ { glee_prologue_cel000, 6 },
	/* 001 */ { glee_prologue_cel001, 6 },
	/* 002 */ { glee_prologue_cel002, 6 },
	/* 003 */ END_ANIMATION
};
