// Generated by N2T

AnimationCel glee_prologue_cel000[] = {
	/* Len */ 2,
	/* 000 */ 0x00e0, 0xc1c0, 0x0000,
	/* 001 */ 0x00e0, 0xc000, 0x0008
};

AnimationCel glee_prologue_cel001[] = {
	/* Len */ 2,
	/* 000 */ 0x00e0, 0xc1c0, 0x0010,
	/* 001 */ 0x00e0, 0xc000, 0x0018
};

AnimationCel glee_prologue_cel002[] = {
	/* Len */ 2,
	/* 000 */ 0x00e0, 0xc1c0, 0x0100,
	/* 001 */ 0x00e0, 0xc000, 0x0108
};
