// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

#include "glee_anim_cells.inc.c"

struct Animation anim_glee_kid_ready[] = {
    /* 000 */ { glee_kid_ready_cel00, 5 },
    /* 001 */ { glee_kid_ready_cel01, 5 },
    /* 002 */ { glee_kid_ready_cel00, 5 },
    /* 003 */ { glee_kid_ready_cel01, 5 },
    /* 004 */ END_ANIMATION,
};

struct Animation anim_glee_kid_look[] = {
    /* 000 */ { glee_kid_look_cel00, 5 },
    /* 001 */ { glee_kid_look_cel01, 5 },
    /* 002 */ { glee_kid_look_cel02, 5 },
    /* 003 */ END_ANIMATION,
};

struct Animation anim_glee_kid_sing_start[] = {
    /* 000 */ { glee_kid_sing_start_cel00, 2 },
    /* 001 */ { glee_kid_sing_start_cel01, 2 },
    /* 002 */ { glee_kid_sing_start_cel02, 2 },
    /* 003 */ END_ANIMATION,
};

struct Animation anim_glee_kid_sing_small[] = {
    /* 000 */ { glee_kid_sing_small_cel00, 6 },
    /* 001 */ { glee_kid_sing_small_cel01, 6 },
    /* 002 */ { glee_kid_sing_small_cel02, 4 },
    /* 003 */ END_ANIMATION,
};

struct Animation anim_glee_kid_sing_large[] = {
    /* 000 */ { glee_kid_sing_large_cel00, 6 },
    /* 001 */ { glee_kid_sing_large_cel01, 6 },
    /* 002 */ { glee_kid_sing_large_cel02, 6 },
    /* 003 */ { glee_kid_sing_large_cel03, 4 },
    /* 004 */ { glee_kid_sing_large_cel04, 4 },
    /* 005 */ { glee_kid_sing_large_cel05, 4 },
    /* 006 */ { glee_kid_sing_small_cel00, 6 },
    /* 007 */ { glee_kid_sing_small_cel01, 6 },
    /* 008 */ { glee_kid_sing_small_cel02, 4 },
    /* 009 */ END_ANIMATION,
};

struct Animation anim_glee_kid_sing_stop[] = {
    /* 000 */ { glee_kid_sing_start_cel02, 2 },
    /* 001 */ { glee_kid_sing_start_cel01, 3 },
    /* 002 */ { glee_kid_sing_start_cel00, 4 },
    /* 003 */ { glee_kid_sing_stop_cel, 5 },
    /* 004 */ { glee_kid_ready_cel00, 5 },
    /* 005 */ { glee_kid_ready_cel01, 5 },
    /* 006 */ { glee_kid_ready_cel00, 5 },
    /* 007 */ { glee_kid_ready_cel01, 5 },
    /* 008 */ { glee_kid_ready_cel00, 5 },
    /* 009 */ { glee_kid_ready_cel01, 5 },
    /* 010 */ END_ANIMATION,
};
