// Generated by N2T

#include "global.h"
#include "graphics.h"
#include "karate_kicks_anim_cells.inc.c"

struct Animation anim_karate_kicks_joe_ready[] = {
	/* 000 */ { karate_kicks_cel010, 24 },
	/* 001 */ END_ANIMATION
};

struct Animation anim_karate_kicks_joe_beat[] = {
	/* 000 */ { karate_kicks_cel014, 3 },
	/* 001 */ { karate_kicks_cel013, 3 },
	/* 002 */ { karate_kicks_cel010, 24 },
	/* 003 */ END_ANIMATION
};

struct Animation anim_karate_kicks_joe_jab[] = {
	/* 000 */ { karate_kicks_cel019, 5 },
	/* 001 */ { karate_kicks_cel020, 2 },
	/* 002 */ { karate_kicks_cel021, 2 },
	/* 003 */ { karate_kicks_cel022, 2 },
	/* 004 */ { karate_kicks_cel014, 1 },
	/* 005 */ END_ANIMATION
};

struct Animation anim_karate_kicks_joe_punch[] = {
	/* 000 */ { karate_kicks_cel023, 2 },
	/* 001 */ { karate_kicks_cel024, 3 },
	/* 002 */ { karate_kicks_cel025, 2 },
	/* 003 */ { karate_kicks_cel026, 2 },
	/* 004 */ { karate_kicks_cel027, 2 },
	/* 005 */ { karate_kicks_cel012, 1 },
	/* 006 */ END_ANIMATION
};

struct Animation anim_karate_kicks_joe_to_ready[] = {
	/* 000 */ { karate_kicks_cel013, 1 },
	/* 001 */ { karate_kicks_cel010, 40 },
	/* 002 */ END_ANIMATION
};

struct Animation anim_karate_kicks_joe_charge[] = {
	/* 000 */ { karate_kicks_cel030, 2 },
	/* 001 */ { karate_kicks_cel031, 30 },
	/* 002 */ END_ANIMATION
};

struct Animation anim_karate_kicks_joe_charge_stop[] = {
	/* 000 */ { karate_kicks_cel033, 3 },
	/* 001 */ { karate_kicks_cel010, 30 },
	/* 002 */ END_ANIMATION
};

struct Animation anim_karate_kicks_joe_kick[] = {
	/* 000 */ { karate_kicks_cel034, 2 },
	/* 001 */ { karate_kicks_cel035, 6 },
	/* 002 */ { karate_kicks_cel036, 4 },
	/* 003 */ { karate_kicks_cel037, 2 },
	/* 004 */ { karate_kicks_cel038, 2 },
	/* 005 */ { karate_kicks_cel039, 2 },
	/* 006 */ { karate_kicks_cel040, 2 },
	/* 007 */ { karate_kicks_cel041, 5 },
	/* 008 */ { karate_kicks_cel032, 0 },
	/* 009 */ { karate_kicks_cel009, 30 },
	/* 010 */ END_ANIMATION
};
