// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

#include "karate_kicks_anim_cells.inc.c"

struct Animation anim_karate_kicks_object[] = {
    /* 000 */ { karate_kicks_object_pot_cel, 1 },
    /* 001 */ { karate_kicks_object_bulb_cel, 1 },
    /* 002 */ { karate_kicks_object_barrel_cel, 1 },
    /* 003 */ { karate_kicks_object_bomb_cel, 1 },
    /* 004 */ END_ANIMATION,
};

struct Animation anim_karate_kicks_barrel_parts[] = {
    /* 000 */ { karate_kicks_barrel_head_cel, 1 },
    /* 001 */ { karate_kicks_barrel_hoop_cel, 1 },
    /* 002 */ { karate_kicks_barrel_stave_cel00, 1 },
    /* 003 */ { karate_kicks_barrel_stave_cel01, 1 },
    /* 004 */ END_ANIMATION,
};

struct Animation anim_karate_kicks_object_shadow[] = {
    /* 000 */ { karate_kicks_object_shadow_cel, 1 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_karate_kicks_hit_effect[] = {
    /* 000 */ { karate_kicks_hit_effect_cel, 2 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_karate_kicks_joe_ready[] = {
    /* 000 */ { karate_kicks_joe_ready_cel, 24 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_karate_kicks_joe_beat[] = {
    /* 000 */ { karate_kicks_joe_beat_cel00, 3 },
    /* 001 */ { karate_kicks_joe_beat_cel01, 3 },
    /* 002 */ { karate_kicks_joe_ready_cel, 24 },
    /* 003 */ END_ANIMATION,
};

struct Animation anim_karate_kicks_joe_jab[] = {
    /* 000 */ { karate_kicks_joe_jab_cel00, 5 },
    /* 001 */ { karate_kicks_joe_jab_cel01, 2 },
    /* 002 */ { karate_kicks_joe_jab_cel02, 2 },
    /* 003 */ { karate_kicks_joe_jab_cel03, 2 },
    /* 004 */ { karate_kicks_joe_beat_cel00, 1 },
    /* 005 */ END_ANIMATION,
};

struct Animation anim_karate_kicks_joe_punch[] = {
    /* 000 */ { karate_kicks_joe_punch_cel00, 2 },
    /* 001 */ { karate_kicks_joe_punch_cel01, 3 },
    /* 002 */ { karate_kicks_joe_punch_cel02, 2 },
    /* 003 */ { karate_kicks_joe_punch_cel03, 2 },
    /* 004 */ { karate_kicks_joe_punch_cel04, 2 },
    /* 005 */ { karate_kicks_joe_punch_cel05, 1 },
    /* 006 */ END_ANIMATION,
};

struct Animation anim_karate_kicks_joe_to_ready[] = {
    /* 000 */ { karate_kicks_joe_beat_cel01, 1 },
    /* 001 */ { karate_kicks_joe_ready_cel, 40 },
    /* 002 */ END_ANIMATION,
};

struct Animation anim_karate_kicks_joe_charge[] = {
    /* 000 */ { karate_kicks_joe_charge_cel00, 2 },
    /* 001 */ { karate_kicks_joe_charge_cel01, 30 },
    /* 002 */ END_ANIMATION,
};

struct Animation anim_karate_kicks_joe_charge_stop[] = {
    /* 000 */ { karate_kicks_joe_charge_stop_cel, 3 },
    /* 001 */ { karate_kicks_joe_ready_cel, 30 },
    /* 002 */ END_ANIMATION,
};

struct Animation anim_karate_kicks_joe_kick[] = {
    /* 000 */ { karate_kicks_joe_kick_cel00, 2 },
    /* 001 */ { karate_kicks_joe_kick_cel01, 6 },
    /* 002 */ { karate_kicks_joe_kick_cel02, 4 },
    /* 003 */ { karate_kicks_joe_kick_cel03, 2 },
    /* 004 */ { karate_kicks_joe_kick_cel04, 2 },
    /* 005 */ { karate_kicks_joe_kick_cel05, 2 },
    /* 006 */ { karate_kicks_joe_kick_cel06, 2 },
    /* 007 */ { karate_kicks_joe_kick_cel07, 5 },
    /* 008 */ { karate_kicks_joe_kick_cel08, 0 },
    /* 009 */ { karate_kicks_joe_kick_cel09, 30 },
    /* 010 */ END_ANIMATION,
};
