// Generated by N2T

#include "global.h"
#include "graphics.h"
#include "cars_prologue_anim_cells.inc.c"

struct Animation anim_cars_prologue_title[] = {
	/* 000 */ { cars_prologue_cel000, 6 },
	/* 001 */ { cars_prologue_cel001, 6 },
	/* 002 */ { cars_prologue_cel002, 6 },
	/* 003 */ END_ANIMATION
};
