// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel cars_revlino_red_cel00[] = {
	/* Len */ 1,
	/* 000 */ 0x40f0, 0xc1e0, 0x0000
};

AnimationCel cars_revlino_red_cel01[] = {
	/* Len */ 1,
	/* 000 */ 0x40f1, 0xc1e0, 0x0000
};

AnimationCel cars_revlino_grey_cel00[] = {
	/* Len */ 1,
	/* 000 */ 0x40f0, 0xc1e0, 0x1000
};

AnimationCel cars_revlino_grey_cel01[] = {
	/* Len */ 1,
	/* 000 */ 0x40f1, 0xc1e0, 0x1000
};

AnimationCel cars_revlino_blue_cel00[] = {
	/* Len */ 1,
	/* 000 */ 0x40f0, 0xc1e0, 0x2000
};

AnimationCel cars_revlino_blue_cel01[] = {
	/* Len */ 1,
	/* 000 */ 0x40f1, 0xc1e0, 0x2000
};

AnimationCel cars_wheel_cel00[] = {
	/* Len */ 1,
	/* 000 */ 0x00f8, 0x41f8, 0x0008
};

AnimationCel cars_wheel_cel01[] = {
	/* Len */ 1,
	/* 000 */ 0x00f8, 0x41f8, 0x0048
};

AnimationCel cars_wheel_cel02[] = {
	/* Len */ 1,
	/* 000 */ 0x00f8, 0x41f8, 0x000a
};

AnimationCel cars_wheel_cel03[] = {
	/* Len */ 1,
	/* 000 */ 0x00f8, 0x41f8, 0x004a
};

AnimationCel cars_wheel_cel04[] = {
	/* Len */ 1,
	/* 000 */ 0x00f8, 0x41f8, 0x000c
};

AnimationCel cars_wheel_cel05[] = {
	/* Len */ 1,
	/* 000 */ 0x00f8, 0x41f8, 0x004c
};
