// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

#include "cars_anim_cells.inc.c"

struct Animation anim_cars_revlino_red[] = {
	/* 000 */ { cars_revlino_red_cel00, 4 },
	/* 001 */ { cars_revlino_red_cel01, 4 },
	/* 002 */ END_ANIMATION,
};

struct Animation anim_cars_revlino_grey[] = {
	/* 000 */ { cars_revlino_grey_cel00, 4 },
	/* 001 */ { cars_revlino_grey_cel01, 4 },
	/* 002 */ END_ANIMATION,
};

struct Animation anim_cars_revlino_blue[] = {
	/* 000 */ { cars_revlino_blue_cel00, 4 },
	/* 001 */ { cars_revlino_blue_cel01, 4 },
	/* 002 */ END_ANIMATION,
};

struct Animation anim_cars_wheel[] = {
	/* 000 */ { cars_wheel_cel00, 2 },
	/* 001 */ { cars_wheel_cel01, 2 },
	/* 002 */ { cars_wheel_cel02, 2 },
	/* 003 */ { cars_wheel_cel03, 2 },
	/* 004 */ { cars_wheel_cel04, 2 },
	/* 005 */ { cars_wheel_cel05, 2 },
	/* 006 */ END_ANIMATION,
};
