// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

#include "shootem_anim_cells.inc.c"

struct Animation anim_shootem_cannon_idle[] = {
    /* 000 */ { shootem_cannon_idle_cel, 24 },
    /* 001 */ END_ANIMATION,
};
