// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

#include "shootem_anim_cells.inc.c"

struct Animation anim_shootem_cannon_idle[] = {
    /* 000 */ { shootem_cannon_idle_cel, 24 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_shootem_cannon_shoot[] = {
    /* 000 */ { shootem_cannon_shoot_cel00, 3 },
    /* 001 */ { shootem_cannon_shoot_cel01, 1 },
    /* 002 */ { shootem_cannon_shoot_cel02, 2 },
    /* 003 */ { shootem_cannon_shoot_cel03, 2 },
    /* 004 */ { shootem_cannon_idle_cel, 18 },
    /* 005 */ END_ANIMATION,
};

struct Animation anim_shootem_cannon_face[] = {
    /* 000 */ { shootem_cannon_face_idle_cel, 1 },
    /* 001 */ { shootem_cannon_face_hurt_cel, 1 },
    /* 002 */ END_ANIMATION,
};

struct Animation anim_shootem_laser_idle[] = {
    /* 000 */ { shootem_empty_cel, 24 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_shootem_laser_shoot[] = {
    /* 000 */ { shootem_laser_shoot_cel00, 3 },
    /* 001 */ { shootem_laser_shoot_cel01, 2 },
    /* 002 */ { shootem_laser_shoot_cel02, 2 },
    /* 003 */ { shootem_laser_shoot_cel03, 2 },
    /* 004 */ { shootem_laser_shoot_cel04, 2 },
    /* 005 */ { shootem_laser_shoot_cel05, 2 },
    /* 006 */ { shootem_laser_shoot_cel06, 2 },
    /* 007 */ { shootem_laser_shoot_cel07, 2 },
    /* 008 */ { shootem_laser_shoot_cel08, 2 },
    /* 009 */ { shootem_empty_cel, 5 },
    /* 010 */ END_ANIMATION,
};

struct Animation anim_shootem_cue_target_idle[] = {
    /* 000 */ { shootem_cue_target_idle_cel00, 16 },
    /* 001 */ { shootem_cue_target_idle_cel01, 16 },
    /* 002 */ { shootem_cue_target_idle_cel02, 16 },
    /* 003 */ { shootem_cue_target_idle_cel03, 16 },
    /* 004 */ { shootem_cue_target_idle_cel04, 16 },
    /* 005 */ { shootem_cue_target_idle_cel05, 16 },
    /* 006 */ { shootem_cue_target_idle_cel06, 16 },
    /* 007 */ { shootem_cue_target_idle_cel07, 16 },
    /* 008 */ { shootem_cue_target_idle_cel08, 16 },
    // /* 009 */ { shootem_cue_target_idle_cel07, 16 },
    // /* 010 */ { shootem_cue_target_idle_cel06, 16 },
    // /* 011 */ { shootem_cue_target_idle_cel05, 16 },
    // /* 012 */ { shootem_cue_target_idle_cel04, 16 },
    // /* 013 */ { shootem_cue_target_idle_cel03, 16 },
    // /* 014 */ { shootem_cue_target_idle_cel02, 16 },
    // /* 015 */ { shootem_cue_target_idle_cel01, 16 },
    /* 016 */ END_ANIMATION,
};

struct Animation anim_shootem_cue_target_hit[] = {
    /* 000 */ { shootem_empty_cel, 24 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_shootem_cue_target_barely[] = {
    /* 000 */ { shootem_empty_cel, 24 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_shootem_cue_target_miss[] = {
    /* 000 */ { shootem_empty_cel, 24 },
    /* 001 */ END_ANIMATION,
};
