// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

#include "qbar_anim_cells.inc.c"

struct Animation anim_qbar_cue[] = {
    /* 000 */ { qbar_cue_blank_cel, 1 },
    /* 001 */ { qbar_cue_5_cel, 2 },
    /* 002 */ { qbar_cue_4_cel, 2 },
    /* 003 */ { qbar_cue_3_cel, 2 },
    /* 004 */ { qbar_cue_2_cel, 2 },
    /* 005 */ { qbar_cue_1_cel, 2 },
    /* 006 */ { qbar_cue_0_cel, 2 },
    /* 007 */ { qbar_cue_neg_1_cel, 2 },
    /* 008 */ { qbar_cue_neg_2_cel, 2 },
    /* 009 */ { qbar_cue_neg_3_cel, 2 },
    /* 010 */ { qbar_cue_neg_4_cel, 2 },
    /* 011 */ { qbar_cue_neg_5_cel, 2 },
    /* 012 */ END_ANIMATION,
};

struct Animation anim_qbar_mark_blank[] = {
    /* 000 */ { qbar_mark_blank_cel, 24 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_qbar_mark_0[] = {
    /* 000 */ { qbar_mark_0_cel, 24 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_qbar_mark_1[] = {
    /* 000 */ { qbar_mark_1_cel, 24 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_qbar_mark_2[] = {
    /* 000 */ { qbar_mark_2_cel, 24 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_qbar_mark_3[] = {
    /* 000 */ { qbar_mark_3_cel, 24 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_qbar_mark_overflow[] = {
    /* 000 */ { qbar_mark_overflow_cel, 24 },
    /* 001 */ END_ANIMATION,
};
